import http from 'node:http';import {readFile} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';
const root=path.join(path.dirname(fileURLToPath(import.meta.url)),'public');const types={'.html':'text/html; charset=utf-8','.css':'text/css','.js':'text/javascript','.webp':'image/webp','.svg':'image/svg+xml','.json':'application/json','.woff2':'font/woff2'};
const limits=new Map();function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data))}
const server=http.createServer(async(req,res)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');try{
 if(req.url==='/health'){return json(res,200,{ok:true})}
 if(req.url==='/api/status'){return json(res,200,{liveAI:!!process.env.OPENAI_API_KEY})}
 if(req.url==='/api/design'&&req.method==='POST'){
 const origin=req.headers.origin;if(origin&&origin!==`https://${req.headers.host}`&&origin!==`http://${req.headers.host}`)return json(res,403,{error:'This request must come from this website.'});
 if(!process.env.OPENAI_API_KEY)return json(res,503,{error:'Live AI is not connected. Explore the interactive design planner below.'});
 const ip=req.socket.remoteAddress;const now=Date.now();const rate=limits.get(ip)||{time:now,count:0};if(now-rate.time>60000){rate.time=now;rate.count=0}if(++rate.count>6)return json(res,429,{error:'Please wait a minute before sending another message.'});limits.set(ip,rate);if(limits.size>2000)limits.clear();
 let body='';for await(const c of req){body+=c;if(body.length>12000)return json(res,413,{error:'Please keep your brief under 3,000 characters.'})}let input;try{input=JSON.parse(body)}catch{return json(res,400,{error:'Invalid request.'})}if(typeof input.message!=='string'||!input.message.trim()||input.message.length>3000)return json(res,400,{error:'Please enter a brief between 1 and 3,000 characters.'});
 const upstream=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-4.1-mini',messages:[{role:'system',content:'You are a helpful residential remodeling design advisor for an illustrative studio concept. Give practical concise design advice grounded in the user\'s room, style and goals. Use up to 180 words. Do not invent business credentials, reviews, exact quotes, site visits, structural feasibility or actions completed. Prices and timings require project-specific professional confirmation. Ask at most one useful follow-up. Never claim an image was generated or an enquiry was sent. Avoid legal, structural or permit approval.'},...(Array.isArray(input.history)?input.history.slice(-6).filter(x=>['user','assistant'].includes(x.role)&&typeof x.content==='string'&&x.content.length<3000):[]),{role:'user',content:input.message}],max_tokens:350}),signal:AbortSignal.timeout(25000)});if(!upstream.ok)return json(res,502,{error:'The design advisor is temporarily unavailable. Your brief is still here.'});const data=await upstream.json();const reply=data.choices?.[0]?.message?.content;if(!reply)return json(res,502,{error:'The advisor returned an empty reply. Please try again.'});return json(res,200,{reply})}
 if(!['GET','HEAD'].includes(req.method))return json(res,405,{error:'Method not allowed.'});let url;try{url=decodeURIComponent(new URL(req.url,'http://localhost').pathname)}catch{return json(res,400,{error:'Invalid path.'})}if(url==='/nova')url='/index.html';else if(url==='/'||url==='/atelier'||url==='/atelier/')url='/atelier/index.html';else if(url.startsWith('/atelier/')&&!path.extname(url))url+='.html';const file=path.resolve(root,'.'+url);if(!file.startsWith(root+path.sep))return json(res,403,{error:'Invalid path.'});let data;try{data=await readFile(file)}catch{if(url.startsWith('/atelier/')){const missing=await readFile(path.join(root,'atelier/404.html'));res.writeHead(404,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-cache'});return res.end(req.method==='HEAD'?undefined:missing)}return json(res,404,{error:'Page not found.'})}res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream','Cache-Control':path.extname(file)==='.html'?'no-cache':'public, max-age=3600'});res.end(req.method==='HEAD'?undefined:data);
}catch(e){json(res,500,{error:'Something went wrong. Please try again.'})}});server.listen(process.env.PORT||3000,'0.0.0.0',()=>console.log('Remodeling samples ready'));
